# Generated by Django 4.1 on 2022-08-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('srimg', models.ImageField(upload_to='pics')),
                ('price', models.PositiveIntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
