# Generated by Django 4.1 on 2022-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ct', models.CharField(max_length=100)),
                ('desc_ct', models.TextField()),
                ('imgct', models.ImageField(upload_to='categ')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='food',
            old_name='update',
            new_name='updated_on',
        ),
    ]
