# Generated by Django 4.1 on 2022-08-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_categorie_rename_update_food_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='categ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.categorie'),
        ),
    ]
